### ISSUE TITLE
Global type definition does not work for TypeScript nodenext modules

### ISSUE THREAD

**Issue by Scrumplex** [3846masa/axios-cookiejar-support#1439]
## Describe the bug

When upgrading to v6, the global type definition for AxiosRequestConfig does not work for setups using `"module": "nodenext"`.

I am almost certain that this is a configuration issue, but this has been the first case where an ESM-only package hasn't worked for me for recent Node.js versions.

## To Reproduce

I have prepared a minimal reproduction example here: https://codesandbox.io/p/devbox/j35z5g

Just run `pnpm build` and observe the type error.

```
src/index.ts:7:41 - error TS2353: Object literal may only specify known properties, and 'jar' does not exist in type 'CreateAxiosDefaults<any>'.

7   const client = wrapper(axios.create({ jar }));
                                          ~~~


Found 1 error in src/index.ts:7
```

The tsconfig base is here: https://github.com/tsconfig/bases/blob/main/bases/node22.json

Note: This does not happpen when `"module": "commonjs"` is set, but that value does not work for my use case.

## Expected behavior

No type error. `jar` is a known property of `AxiosRequestConfig`

## Code that reproduces the bug

See my minimal reproduction above

## Environments

- OS: Linux (DevContainer, but also happens on macOS and Linux natively)
- Node.js version: 22.16.0
- axios version: 1.11.0
- tough-cookie version: 5.1.2

**Comment by Scrumplex** [comment]
A workaround I have found is to paste the following type definition into my code:

https://github.com/3846masa/axios-cookiejar-support/blob/c9987665f16a4ad00baed3e5c88439b5edb2068e/src/index.ts#L11-L15

**Comment by 3846masa** [comment]
Sorry for the delay in responding.

This problem is not an axios-cookiejar-support issue, but is caused by axios providing separate type definition files for CommonJS and ESModules.

If you don't have `“type”: “module”` in your code package.json, your code tries to load axios as CommonJS and the type definition files are loaded from CommonJS.

However, the package.json of axios-cookiejar-support contains `“type”: “module”`, so the type definition file is loaded from ESModules.

It is considered that the reported problem is happening because the axios type definitions being read are different.

The problem can be solved by one of the following

a.) Put `“type”: “module”` in the package.json of your code.
* If your code runs directly in Node.js, this is recommended.

b.) Specify `module“: ”esnext“, ‘moduleResolution’: ”bundler"` in tsconfig.json
* If your code will be written to a separate JavaScript file through some bundling tool, this is recommended

> Translated with DeepL.com (free version)
